# Generated by Django 6.0.3 on 2026-03-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('distance_from_airport', models.DecimalField(decimal_places=1, help_text='Distance in km', max_digits=5)),
                ('amenities', models.JSONField(default=list)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_type', models.CharField(choices=[('budget', 'Budget'), ('luxury', 'Luxury')], max_length=20)),
            ],
        ),
    ]
