# Generated by Django 6.0.3 on 2026-03-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
