# Generated by Django 6.0.3 on 2026-03-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_passenger_email_passenger_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
