# Generated by Django 6.0.3 on 2026-04-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='allocated_seats',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
