# Generated by Django 6.0.3 on 2026-03-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('seating_capacity', models.IntegerField(default=4)),
                ('cab_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
