# Generated by Django 6.0.3 on 2026-03-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='available_seats',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='flight',
            name='total_seats',
            field=models.IntegerField(default=180),
        ),
    ]
