# Generated by Django 6.0.3 on 2026-03-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_available_seats_flight_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='booked_seats',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
